# Generated by Django 2.2 on 2020-11-04 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='제목')),
                ('category', models.CharField(max_length=20, verbose_name='카테고리')),
                ('content', models.TextField(verbose_name='내용')),
                ('recommendation', models.IntegerField(verbose_name='추천')),
                ('opposition', models.IntegerField(verbose_name='반대')),
                ('hits', models.IntegerField(verbose_name='추천수')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='작성시간')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Profile')),
            ],
        ),
    ]
