# Generated by Django 2.2 on 2020-11-04 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_tokens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='category',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='카테고리'),
        ),
        migrations.AlterField(
            model_name='board',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='내용'),
        ),
        migrations.AlterField(
            model_name='board',
            name='title',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='제목'),
        ),
    ]
