# Generated by Django 2.2 on 2020-11-09 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20201109_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='line_cnt',
        ),
        migrations.AddField(
            model_name='comment',
            name='like_cnt',
            field=models.IntegerField(default=0, verbose_name='좋아요수'),
        ),
    ]
