# Generated by Django 2.2.7 on 2020-11-24 12:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_auto_20201124_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hitcount',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 11, 24, 12, 40, 0, 280195), null=True),
        ),
    ]
