# Generated by Django 2.0.5 on 2021-08-10 21:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_auto_20201124_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hitcount',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 8, 10, 21, 10, 34, 468492), null=True),
        ),
    ]
