# Generated by Django 2.2.7 on 2020-11-24 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster_img', models.ImageField(upload_to='info/')),
                ('homepage_url', models.CharField(max_length=300)),
            ],
        ),
    ]
