# Generated by Django 2.2.7 on 2020-11-24 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='datetime',
            field=models.DateTimeField(auto_now=True, verbose_name='작성시간'),
        ),
    ]
