# Generated by Django 2.2 on 2020-11-09 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20201104_1801'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_cnt', models.IntegerField(default=0, verbose_name='좋아요수')),
                ('content', models.TextField(verbose_name='내용')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='작성시간')),
                ('parent_id', models.IntegerField(default=0, verbose_name='부모아이디')),
            ],
        ),
        migrations.RemoveField(
            model_name='board',
            name='opposition',
        ),
        migrations.RemoveField(
            model_name='board',
            name='recommendation',
        ),
        migrations.AddField(
            model_name='board',
            name='like_like',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='좋아요수'),
        ),
        migrations.AlterField(
            model_name='board',
            name='hits',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='조회수'),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Board')),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Board'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Profile'),
        ),
    ]
