# Generated by Django 2.2 on 2020-11-09 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20201109_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='parent_id',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='부모아이디'),
        ),
    ]
