# Generated by Django 2.2 on 2020-11-13 22:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_hitcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='isNotifications',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='hitcount',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 11, 13, 22, 45, 31, 584809, tzinfo=utc), null=True),
        ),
    ]
