# Generated by Django 2.2 on 2020-11-13 23:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20201114_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentnotification',
            name='isNotification',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recommentnotification',
            name='isNotification',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='hitcount',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 11, 13, 23, 52, 13, 445697, tzinfo=utc), null=True),
        ),
    ]
