# Generated by Django 2.2 on 2020-11-13 23:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20201114_0852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommentnotification',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='recommentnotification',
            name='recomment',
        ),
        migrations.RemoveField(
            model_name='recommentnotification',
            name='user',
        ),
        migrations.AddField(
            model_name='comment',
            name='isNotification',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='hitcount',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 11, 13, 23, 59, 38, 216555, tzinfo=utc), null=True),
        ),
        migrations.DeleteModel(
            name='CommentNotification',
        ),
        migrations.DeleteModel(
            name='RecommentNotification',
        ),
    ]
