# Generated by Django 2.2.7 on 2020-11-17 12:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20201117_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageroom',
            name='user1_isDelete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='messageroom',
            name='user2_isDelete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='hitcount',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 11, 17, 12, 41, 42, 712499), null=True),
        ),
    ]
