# Generated by Django 2.2 on 2020-11-18 06:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20201117_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messageroom',
            name='user1_isDelete',
        ),
        migrations.RemoveField(
            model_name='messageroom',
            name='user2_isDelete',
        ),
        migrations.AddField(
            model_name='message',
            name='receive_isDelete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='send_isDelete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='hitcount',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 11, 18, 6, 16, 44, 689316), null=True),
        ),
    ]
