# Generated by Django 2.2 on 2020-11-19 15:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20201118_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='isNotification',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='hitcount',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 11, 19, 15, 11, 30, 896738), null=True),
        ),
    ]
