# Generated by Django 2.0.5 on 2021-08-11 11:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_auto_20210811_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hitcount',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 8, 11, 11, 38, 32, 331883), null=True),
        ),
    ]
