# Generated by Django 2.0.5 on 2021-08-11 11:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_auto_20210811_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='category',
            field=models.CharField(blank=True, choices=[('1', '채소'), ('2', '과일'), ('3', '특수작물'), ('4', '뿌리'), ('5', '줄기'), ('6', '기타'), ('7', '자유게시판'), ('8', '공유게시판'), ('9', '정부지원'), ('10', '주말농장'), ('11', '작물판매'), ('12', '공유농업일지')], max_length=4, null=True, verbose_name='카테고리'),
        ),
        migrations.AlterField(
            model_name='hitcount',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 8, 11, 11, 42, 17, 683479), null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='category',
            field=models.CharField(blank=True, choices=[('1', '채소'), ('2', '과일'), ('3', '특수작물'), ('4', '뿌리'), ('5', '줄기'), ('6', '기타'), ('7', '자유게시판'), ('8', '공유게시판'), ('9', '정부지원'), ('10', '주말농장'), ('11', '작물판매'), ('12', '공유농업일지')], max_length=4, null=True, verbose_name='관심분야'),
        ),
    ]
